# Which worlds should this plugin be enabled in? Worlds not in this list will be ignored
enabled_worlds:
  - example_world
  - example_world_nether
  
# Message prefix, for messages sent to players by the plugin
# Available colors: AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_PURPLE, DARK_RED, GOLD, GRAY, GREEN, LIGHT_PURPLE, RED, WHITE, YELLOW
prefix_enabled: true
prefix_msg: "ResPwn"
prefix_msg_color: "GOLD"
prefix_wrap_front: "["
prefix_wrap_back: "]"
prefix_wrap_color: "RED"

# Respawn shield timer setting, set this to how long the player gets shield on respawn (in seconds)
respawn_shield_timer: 20

# If shielded player attacks an unshielded player or mob, the spawn shield is removed. 
clear_on_attack: true

# No teleport timer setting, set this to how long players cannot teleport after respawn (in seconds)
respawn_tpshield_timer: 20

# No command use timer setting, set this to how long players cannot use commands after respawn (in seconds)
respawn_cmdshield_timer: 20

# The player's health level be on respawn - max 20
respawn_health: 20

# The player's hunger level be on respawn - max 20
respawn_hunger: 20

# Set an armor delay, to only allow respawned players to get armor/wield kit every X seconds. 60 = 1 minute, 600 = 10 minutes, 3600 = 1 hour...
armor_delay: 600

# Player armor on respawn - use official item names only!
# If armor is leather, you can set a color here using hex code eg: 0x000000
# For enchants use official bukkit enchant names only, unsafe enchants will be ignored
respawn_armor:
    boots: 
        use: false
        type: LEATHER_BOOTS
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1
        name: "Starter Boots"
        lore: 
            - "Starter boots lore"
        color: 0x00FF00           
    helm: 
        use: false
        type: LEATHER_HELMET
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1
        name: "Starter Helm"
        lore: 
            - "Starter helm lore"
        color: 0x00FF00            
    pants: 
        use: false
        type: LEATHER_LEGGINGS
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1
        name: "Starter Pants"
        lore: 
            - "Starter pants lore"
        color: 0x00FF00          
    plate: 
        use: false
        type: LEATHER_CHESTPLATE
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1
        name: "Starter Vest"
        lore: 
            - "Starter vest lore"
        color: 0x00FF00

# Player item in MAIN hand on respawn - use official item names only!
respawn_wield: 
    use: false
    item: WOOD_SWORD
    enchants: 
        KNOCKBACK: 1
    name: "Starter Sword"
    lore:
        - "Starter sword lore"

# Player item in MAIN hand on respawn - use official item names only!
respawn_offhand: 
    use: false
    item: TORCH
    enchants: []
    name: "A light"
    lore:
        - "in case it's dark out"
        
# duration is in TICKS. 20 ticks = 1 second. This will set potion effects on player after respawn.
respawn_potions:
    INVISIBILITY: 
        duration: 400
        amplifier: 1
    SPEED: 
        duration: 400
        amplifier: 1    

# Run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false  