# Which worlds should this plugin be enabled in? Worlds not in this list will be ignored
enabled_worlds:
  - example_world
  - example_world_nether
  
# Respawn shield timer setting, set this to how long the player gets shield on respawn (in seconds)
respawn_shield_timer: 20

# If shielded player attacks an unshielded player or mob, the spawn shield is removed. 
clear_on_attack: false

# The player's health level be on respawn - max 20
respawn_health: 20

# The player's hunger level be on respawn - max 20
respawn_hunger: 20

# Player armor on respawn - use official item names only!
respawn_armor:
    boots: 
        type: LEATHER_BOOTS
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1    
    helm: 
        type: LEATHER_HELMET
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1
    pants: 
        type: LEATHER_LEGGINGS
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1
    plate: 
        type: LEATHER_CHESTPLATE
        enchants: 
            PROTECTION_ENVIRONMENTAL: 1

# Player item in hand on respawn - use official item names only!
respawn_wield: 
    item: WOOD_SWORD
    enchants: 
        KNOCKBACK: 1

# Run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false  