main: com.pwn9.ResPwn.ResPwn
name: ResPwn
version: 1.0
author: tremor77
description: Player respawn timer with various settings for gameplay.
website: http://pwn9.com
permissions:
  respwn.shield: 
    description: Player will receive ResPwn combat shield
  respwn.tpshield:
    description: Player will receive ResPwn teleport shield
  respwn.cmdshield:
    description: Player will receive ResPwn command shield    
  respwn.health:
    description: Player will receive ResPwn health level
  respwn.hunger:
    description: Player will receive ResPwn hunger level
  respwn.armor:
    description: Player will receive ResPwn armor sets
  respwn.wield:
    description: Player will receive ResPwn item in hand 
  respwn.potions:
    description: Player will receive ResPwn potion effects